### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by serhattsnmz** [mnesarco/FreeCAD_ExtMan#7]
Hi,

When I download ExtMan and restart FreeCAD, I am getting following error:

```
During initialization the error No module named 'PySide2.QtWebEngineCore' occurred in freecad.extman
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 145, in InitApplications
  File "C:\Program Files\FreeCAD 0.18\bin\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files\FreeCAD 0.18\Mod\ExtMan\freecad\extman\init_gui.py", line 26, in <module>
    from freecad.extman.gui.browser import install_router, start_browser
  File "C:\Program Files\FreeCAD 0.18\Mod\ExtMan\freecad\extman\gui\browser.py", line 28, in <module>
    from freecad.extman.gui.webview import WebView
  File "C:\Program Files\FreeCAD 0.18\Mod\ExtMan\freecad\extman\gui\webview.py", line 30, in <module>
    from PySide2.QtWebEngineCore import QWebEngineUrlSchemeHandler
ModuleNotFoundError: No module named 'PySide2.QtWebEngineCore'
--------------------------------------------------------------------------------
```

**Comment by mnesarco** [comment]
Check the installation requirements  (in readme)

python3-pyside2.qtwebchannel
python3-pyside2.qtnetwork
python3-pyside2.qtwebenginecore
python3-pyside2.qtwebenginewidgets

**Comment by serhattsnmz** [comment]
I think it is not working on windows. Cause the requirements not suitable for windows.

**Comment by mnesarco** [comment]
It works on windows. Just install the conda version. Remember that this requires FreeCAD 0.19

**Comment by serhattsnmz** [comment]
It works on FreeCAD 0.19. 
It'd be better if you add that information on readme file. 

Thanks @mnesarco

**Comment by mnesarco** [comment]
Ok, done. Thank you.
