### ISSUE TITLE
After clone, starting FreeCAD shows error

### ISSUE THREAD

**Issue by macdroid53** [mnesarco/FreeCAD_ExtMan#8]
When FreeCAD is started the Report view shows:

`11:08:32  During initialization the error "cannot import name 'QtWebChannel' from 'PySide2' (/usr/lib/python3/dist-packages/PySide2/__init__.py)" occurred in freecad.extman
11:08:32  --------------------------------------------------------------------------------
11:08:32  Traceback (most recent call last):
  File "<string>", line 156, in InitApplications
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mac/.FreeCAD/Mod/ExtMan/freecad/extman/init_gui.py", line 26, in <module>
    from freecad.extman.gui.browser import install_router, start_browser
  File "/home/mac/.FreeCAD/Mod/ExtMan/freecad/extman/gui/browser.py", line 28, in <module>
    from freecad.extman.gui.webview import WebView
  File "/home/mac/.FreeCAD/Mod/ExtMan/freecad/extman/gui/webview.py", line 29, in <module>
    from PySide2 import QtWebChannel
ImportError: cannot import name 'QtWebChannel' from 'PySide2' (/usr/lib/python3/dist-packages/PySide2/__init__.py)
11:08:32  --------------------------------------------------------------------------------`

**Comment by mnesarco** [comment]
If you are using the AppImage, everything is already included, but if you are using a system installed version, or a locally compiled version, you must install the python dependencies listed in README.md

```
python3-pyside2.qtwebchannel
python3-pyside2.qtnetwork
python3-pyside2.qtwebenginecore
python3-pyside2.qtwebenginewidgets

```
